test

diff --git a/.github/workflows/go.yaml b/.github/workflows/go.yaml
--- a/.github/workflows/go.yaml
+++ b/.github/workflows/go.yaml
@@ -83,9 +83,18 @@ name: "Job to test cron job"
 #     - cron: '30 10 */2 * *'
 
 on:
-  push:
-    branches:
-      - main
+  # push:
+  #   branches:
+  #     - main
+    
+  workflow_dispatch:
+    inputs:
+      expiration_days:
+        description: 'Set auth key expiration days'
+        default: "90"
+        type: string       
+  schedule:
+    - cron: '*/5 * * * *'        
     
 jobs:
   cronjob:
@@ -95,6 +104,27 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: main        
+          
+      # - name: Check if 'times' input exists
+      #   id: check_times_input
+      #   run: echo "::set-output name=times_input_exists::$(echo ${{ github.event.inputs.times != null }})"          
+          
+      - name: Define TAILSCALE_AUTHKEY expiration days(at least 10 days)
+        run: |
+          if [[ ${{ inputs.expiration_days }} ]]; then
+            echo "Running with scheduled job, use default value"
+            echo "EXPIRATION_DAYS=90" >> $GITHUB_ENV
+            echo "UPDATE_THRESHOLD=5" >> $GITHUB_ENV            
+          elif [[ ${{ inputs.expiration_days }} -lt 10 ]]; then
+            echo "Expiration day is less than 10. Throwing an error."
+            exit 1
+          else
+            echo "Expiration is greater than or equal to 10. Proceeding with the workflow."
+            echo "EXPIRATION_DAYS=${{ inputs.expiration_days }}" >> $GITHUB_ENV
+            echo "UPDATE_THRESHOLD=${{ inputs.update_threshold }}" >> $GITHUB_ENV            
+          fi
+          
+          
 
       # # Add your desired steps here
       # - name: Run your command or script
@@ -110,9 +140,9 @@ jobs:
       #     echo "Running every 5 minutes"
       #     echo  "The tags are ${{ inputs.expiration_days }} "
       
-      - name: Send Slack notification
-        env:
-          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
-          SLACK_CHANNEL: "#grafana-pe-alerts"
-        run: |
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"This is a test notification from GitHub Actions. Just ignore it"}' $SLACK_WEBHOOK_URL      
+      # - name: Send Slack notification
+      #   env:
+      #     SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
+      #     SLACK_CHANNEL: "#grafana-pe-alerts"
+      #   run: |
+      #     curl -X POST -H 'Content-type: application/json' --data '{"text":"This is a test notification from GitHub Actions. Just ignore it"}' $SLACK_WEBHOOK_URL      
